//    SugarCubes - composable workflow units for ComfyUI
//    Copyright (C) 2026  Artificial Sweetener and contributors
//
//    This program is free software: you can redistribute it and/or modify
//    it under the terms of the GNU Affero General Public License as published by
//    the Free Software Foundation, either version 3 of the License, or
//    (at your option) any later version.
//
//    This program is distributed in the hope that it will be useful,
//    but WITHOUT ANY WARRANTY; without even the implied warranty of
//    MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
//    GNU Affero General Public License for more details.
//
//    You should have received a copy of the GNU Affero General Public License
//    along with this program.  If not, see <https://www.gnu.org/licenses/>.
/**
 * Own the SugarCubes dialog presentation layer in `web/comfyui/ui/dialogs/DialogStyles.js`.
 */
const STYLE_ID = 'sugarcubes-dialog-styles';
const dialogStyles = [
    '.sugarcubes-modal-overlay,',
    '.sugarcubes-version-overlay {',
    '  position: fixed;',
    '  inset: 0;',
    '  z-index: 10000;',
    '  display: none;',
    '  align-items: center;',
    '  justify-content: center;',
    '  background: rgba(0, 0, 0, 0.45);',
    '}',
    '',
    '.sugarcubes-modal-overlay.is-visible,',
    '.sugarcubes-version-overlay.is-visible {',
    '  display: flex;',
    '}',
    '',
    '.sugarcubes-create-cube-overlay {',
    '  align-items: flex-end;',
    '  padding: 0 16px min(12vh, 96px);',
    '  box-sizing: border-box;',
    '}',
    '',
    '.sugarcubes-modal,',
    '.sugarcubes-version-dialog {',
    '  max-width: min(90vw, 520px);',
    '  width: 100%;',
    '  max-height: min(80vh, 760px);',
    '  overflow: auto;',
    '}',
    '',
    '.sugarcubes-pack-manager-dialog {',
    '  max-width: min(92vw, 860px);',
    '}',
    '',
    '.sugarcubes-create-cube-dialog {',
    '  max-width: min(92vw, 640px);',
    '}',
    '',
    '.sugarcubes-modal__description {',
    '  display: grid;',
    '  gap: 8px;',
    '  margin-bottom: 12px;',
    '}',
    '',
    '.sugarcubes-modal__description p,',
    '.sugarcubes-modal__field-help,',
    '.sugarcubes-selection-dialog__option-description,',
    '.sugarcubes-selection-dialog__empty,',
    '.sugarcubes-modal__error,',
    '.sugarcubes-modal__field-error {',
    '  margin: 0;',
    '  font-size: 12px;',
    '  line-height: 1.45;',
    '}',
    '',
    '.sugarcubes-modal__error,',
    '.sugarcubes-modal__field-error {',
    '  color: #ff8a8a;',
    '  display: none;',
    '}',
    '',
    '.sugarcubes-modal__error:not(:empty),',
    '.sugarcubes-modal__field-error:not(:empty) {',
    '  display: block;',
    '}',
    '',
    '.sugarcubes-modal__field,',
    '.sugarcubes-modal__form {',
    '  display: grid;',
    '  gap: 10px;',
    '}',
    '',
    '.sugarcubes-modal__field-label,',
    '.sugarcubes-modal__checkbox-label,',
    '.sugarcubes-selection-dialog__option-title {',
    '  font-size: 12px;',
    '  font-weight: 600;',
    '}',
    '',
    '.sugarcubes-modal__text-input {',
    '  width: 100%;',
    '}',
    '',
    '.sugarcubes-modal__field--checkbox {',
    '  grid-template-columns: auto 1fr;',
    '  align-items: center;',
    '  column-gap: 8px;',
    '}',
    '',
    '.sugarcubes-create-cube__preview {',
    '  display: grid;',
    '  gap: 8px;',
    '  padding: 10px 12px;',
    '  border: 1px solid rgba(160, 180, 205, 0.25);',
    '  border-radius: 8px;',
    '  background: rgba(27, 35, 48, 0.66);',
    '}',
    '',
    '.sugarcubes-create-cube__row {',
    '  display: grid;',
    '  grid-template-columns: 96px minmax(0, 1fr);',
    '  gap: 10px;',
    '  align-items: start;',
    '  font-size: 12px;',
    '}',
    '',
    '.sugarcubes-create-cube__label {',
    '  opacity: 0.72;',
    '}',
    '',
    '.sugarcubes-create-cube__value {',
    '  min-width: 0;',
    '  overflow-wrap: anywhere;',
    '}',
    '',
    '.sugarcubes-create-cube__description {',
    '  min-height: 74px;',
    '  resize: vertical;',
    '}',
    '',
    '.sugarcubes-create-cube__warnings {',
    '  margin: 0;',
    '  padding-left: 18px;',
    '  font-size: 12px;',
    '  line-height: 1.45;',
    '}',
    '',
    '.sugarcubes-modal__footer {',
    '  display: flex;',
    '  justify-content: space-between;',
    '  align-items: center;',
    '  gap: 12px;',
    '}',
    '',
    '.sugarcubes-modal__footer-meta {',
    '  flex: 1 1 auto;',
    '}',
    '',
    '.sugarcubes-modal__footer-actions {',
    '  display: inline-flex;',
    '  gap: 8px;',
    '  align-items: center;',
    '}',
    '',
    '.sugarcubes-selection-dialog__list {',
    '  display: grid;',
    '  gap: 8px;',
    '}',
    '',
    '.sugarcubes-selection-dialog__option {',
    '  display: grid;',
    '  grid-template-columns: auto 1fr;',
    '  gap: 10px;',
    '  align-items: start;',
    '  padding: 10px 12px;',
    '  border: 1px solid rgba(160, 180, 205, 0.25);',
    '  border-radius: 8px;',
    '  background: rgba(27, 35, 48, 0.66);',
    '}',
    '',
    '.sugarcubes-selection-dialog__option-copy {',
    '  display: grid;',
    '  gap: 4px;',
    '}',
    '',
    '.sugarcubes-version-dialog__dismiss {',
    '  display: inline-flex;',
    '  align-items: center;',
    '  gap: 8px;',
    '  font-size: 12px;',
    '}',
];
/**
 * Inject dialog styles.
 */
export function injectDialogStyles(documentRef) {
    if (!documentRef?.head || documentRef.getElementById(STYLE_ID)) {
        return;
    }
    const style = documentRef.createElement('style');
    style.id = STYLE_ID;
    style.textContent = dialogStyles.join('\n');
    documentRef.head.appendChild(style);
}
