//    SugarCubes - composable workflow units for ComfyUI
//    Copyright (C) 2026  Artificial Sweetener and contributors
//
//    This program is free software: you can redistribute it and/or modify
//    it under the terms of the GNU Affero General Public License as published by
//    the Free Software Foundation, either version 3 of the License, or
//    (at your option) any later version.
//
//    This program is distributed in the hope that it will be useful,
//    but WITHOUT ANY WARRANTY; without even the implied warranty of
//    MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
//    GNU Affero General Public License for more details.
//
//    You should have received a copy of the GNU Affero General Public License
//    along with this program.  If not, see <https://www.gnu.org/licenses/>.
/**
 * Own the SugarCubes cube browser layer in `frontend/comfyui/ui/browser/BrowserStyles.js`.
 */
const STYLE_ID = 'sugarcubes-browser-styles';
/**
 * Expose the browser styles constant.
 */
export const browserStyles = [
    '.sugarcubes-browser {',
    '    --sugarcubes-pack-row-bg: rgba(86, 96, 82, 0.16);',
    '    --sugarcubes-pack-row-bg-collapsed: rgba(86, 96, 82, 0.1);',
    '    --sugarcubes-pack-row-hover: rgba(86, 96, 82, 0.22);',
    '    --sugarcubes-pack-count-bg: rgba(128, 128, 128, 0.16);',
    '    --sugarcubes-cube-row-bg: rgba(128, 128, 128, 0.02);',
    '    --sugarcubes-cube-row-alt-bg: rgba(128, 128, 128, 0.07);',
    '    --sugarcubes-cube-row-hover: rgba(99, 179, 237, 0.18);',
    '    --sugarcubes-cube-row-selected: rgba(99, 179, 237, 0.25);',
    '    width: 100%;',
    '    max-height: none;',
    '    background: transparent;',
    '    color: inherit;',
    '    display: flex;',
    '    flex-direction: column;',
    '    border-radius: 0;',
    '    box-shadow: none;',
    '    overflow: hidden;',
    '}',
    'body.dark-theme .sugarcubes-browser {',
    '    --sugarcubes-browser-bg: #121417;',
    '    --sugarcubes-pack-row-bg: rgba(92, 101, 86, 0.2);',
    '    --sugarcubes-pack-row-bg-collapsed: rgba(92, 101, 86, 0.13);',
    '    --sugarcubes-pack-row-hover: rgba(92, 101, 86, 0.28);',
    '    --sugarcubes-pack-count-bg: rgba(255, 255, 255, 0.1);',
    '    --sugarcubes-cube-row-bg: rgba(255, 255, 255, 0.015);',
    '    --sugarcubes-cube-row-alt-bg: rgba(255, 255, 255, 0.045);',
    '}',
    '.sugarcubes-browser__list,',
    '.sugarcubes-browser__detail {',
    '    border-radius: 10px;',
    '}',
    '.sugarcubes-browser__list {',
    '    max-height: 280px;',
    '    overflow-y: auto;',
    '}',
    '.sugarcubes-browser__table thead {',
    '    display: none;',
    '}',
    '.sugarcubes-browser__detail {',
    '    max-height: 240px;',
    '}',
    '.sugarcubes-browser__table th:nth-child(2),',
    '.sugarcubes-browser__table td:nth-child(2),',
    '.sugarcubes-browser__table th:nth-child(3),',
    '.sugarcubes-browser__table td:nth-child(3),',
    '.sugarcubes-browser__table th:nth-child(4),',
    '.sugarcubes-browser__table td:nth-child(4) {',
    '    display: none;',
    '}',
    '.sugarcubes-browser__content {',
    '    display: flex;',
    '    flex-direction: column;',
    '    gap: 16px;',
    '    padding: 0 0 10px;',
    '    overflow: hidden;',
    '}',
    '.sugarcubes-browser__list {',
    '    flex: 1 1 55%;',
    '    min-width: 0;',
    '    display: flex;',
    '    flex-direction: column;',
    '    border: 1px solid rgba(128, 128, 128, 0.18);',
    '    border-radius: 12px;',
    '    overflow: hidden;',
    '}',
    '.sugarcubes-browser__list-header {',
    '    display: flex;',
    '    align-items: center;',
    '    padding: 8px 10px;',
    '    background: rgba(128, 128, 128, 0.08);',
    '    border-bottom: 1px solid rgba(128, 128, 128, 0.18);',
    '}',
    '.sugarcubes-browser__list-header .sugarcubes-browser__search {',
    '    display: inline-flex;',
    '    align-items: center;',
    '    width: 100%;',
    '}',
    '.sugarcubes-browser__list-header input {',
    '    width: 100%;',
    '}',
    '.sugarcubes-browser__list-body {',
    '    display: flex;',
    '    flex-direction: column;',
    '    overflow-y: auto;',
    '}',
    '.sugarcubes-browser__author-toggle {',
    '    border: none;',
    '    background: var(--sugarcubes-pack-row-bg);',
    '    color: inherit;',
    '    display: flex;',
    '    align-items: center;',
    '    justify-content: space-between;',
    '    gap: 8px;',
    '    padding: 8px 12px;',
    '    cursor: pointer;',
    '    font-size: 0.85rem;',
    '    font-weight: 600;',
    '    text-align: left;',
    '}',
    '.sugarcubes-browser__author-toggle[aria-expanded="false"] {',
    '    background: var(--sugarcubes-pack-row-bg-collapsed);',
    '}',
    '.sugarcubes-browser__author-toggle:hover {',
    '    background: var(--sugarcubes-pack-row-hover);',
    '}',
    '.sugarcubes-browser__author-toggle + .sugarcubes-browser__author-list {',
    '    border-bottom: 1px solid rgba(128, 128, 128, 0.12);',
    '}',
    '.sugarcubes-browser__pack-label {',
    '    display: flex;',
    '    align-items: baseline;',
    '    gap: 8px;',
    '    overflow: hidden;',
    '    min-width: 0;',
    '}',
    '.sugarcubes-browser__pack-name,',
    '.sugarcubes-browser__pack-author {',
    '    overflow: hidden;',
    '    text-overflow: ellipsis;',
    '    white-space: nowrap;',
    '}',
    '.sugarcubes-browser__pack-name {',
    '    font-weight: 600;',
    '}',
    '.sugarcubes-browser__pack-author {',
    '    font-size: 0.74rem;',
    '    font-weight: 400;',
    '    opacity: 0.62;',
    '}',
    '.sugarcubes-browser__author-count {',
    '    font-size: 0.75rem;',
    '    opacity: 0.65;',
    '    padding: 2px 8px;',
    '    border-radius: 999px;',
    '    background: var(--sugarcubes-pack-count-bg);',
    '}',
    '.sugarcubes-browser__author-list {',
    '    display: flex;',
    '    flex-direction: column;',
    '    border-left: 1px solid rgba(128, 128, 128, 0.14);',
    '    margin-left: 12px;',
    '}',
    '.sugarcubes-browser__author-list.is-collapsed {',
    '    display: none;',
    '}',
    '.sugarcubes-browser__cube-row {',
    '    display: flex;',
    '    align-items: center;',
    '    justify-content: space-between;',
    '    gap: 10px;',
    '    padding: 8px 12px 8px 18px;',
    '    background: var(--sugarcubes-cube-row-bg);',
    '    cursor: pointer;',
    '}',
    '.sugarcubes-browser__author-list .sugarcubes-browser__cube-row:nth-child(even) {',
    '    background: var(--sugarcubes-cube-row-alt-bg);',
    '}',
    '.sugarcubes-browser__author-list .sugarcubes-browser__cube-row:hover {',
    '    background: var(--sugarcubes-cube-row-hover);',
    '}',
    '.sugarcubes-browser__cube-row.is-selected {',
    '    background: var(--sugarcubes-cube-row-selected);',
    '}',
    '.sugarcubes-browser__author-list .sugarcubes-browser__cube-row.is-selected,',
    '.sugarcubes-browser__author-list .sugarcubes-browser__cube-row.is-selected:hover {',
    '    background: var(--sugarcubes-cube-row-selected);',
    '}',
    '.sugarcubes-browser__cube-row:hover {',
    '    background: var(--sugarcubes-cube-row-hover);',
    '}',
    '.sugarcubes-browser__cube-row.is-selected:hover {',
    '    background: var(--sugarcubes-cube-row-selected);',
    '}',
    '.sugarcubes-browser__cube-title {',
    '    display: inline-flex;',
    '    align-items: center;',
    '    gap: 6px;',
    '    font-weight: 600;',
    '    min-width: 0;',
    '  }',
    '.sugarcubes-cube-icon {',
    '    width: 24px;',
    '    height: 24px;',
    '    flex: 0 0 24px;',
    '    display: inline-flex;',
    '    align-items: center;',
    '    justify-content: center;',
    '    color: #fff;',
    '    font-size: 0.68rem;',
    '    font-weight: 700;',
    '    line-height: 1;',
    '    overflow: hidden;',
    '}',
    '.sugarcubes-cube-icon img {',
    '    width: 100%;',
    '    height: 100%;',
    '    object-fit: contain;',
    '}',
    '.sugarcubes-cube-icon__fallback {',
    '    width: 100%;',
    '    height: 100%;',
    '    display: block;',
    '}',
    '.sugarcubes-cube-icon.is-generic::before {',
    '    content: "";',
    '    width: 12px;',
    '    height: 12px;',
    '    border: 1.5px solid currentColor;',
    '    box-sizing: border-box;',
    '    transform: skewY(-12deg);',
    '}',
    '.sugarcubes-browser__cube-title-text {',
    '    min-width: 0;',
    '    overflow: hidden;',
    '    text-overflow: ellipsis;',
    '    white-space: nowrap;',
    '}',
    '.sugarcubes-browser__cube-row.is-dirty .sugarcubes-browser__cube-title {',
    '    font-weight: 700;',
    '}',
    '.sugarcubes-browser__table {',
    '    width: 100%;',
    '    border-collapse: collapse;',
    '    font-size: 0.92rem;',
    '}',
    '.sugarcubes-browser__table thead {',
    '    background: rgba(128, 128, 128, 0.1);',
    '}',
    '.sugarcubes-browser__table th, .sugarcubes-browser__table td {',
    '    padding: 10px 12px;',
    '    text-align: left;',
    '}',
    '.sugarcubes-browser__table th:empty {',
    '    padding: 0;',
    '}',
    '.sugarcubes-browser__table th:last-child,',
    '.sugarcubes-browser__table td:last-child {',
    '    text-align: right;',
    '    width: 32px;',
    '}',
    '.sugarcubes-browser__table tbody tr {',
    '    cursor: pointer;',
    '}',
    '.sugarcubes-browser__table tbody tr:nth-child(even) {',
    '    background: rgba(128, 128, 128, 0.06);',
    '}',
    '.sugarcubes-browser__table tbody tr.is-selected {',
    '    background: rgba(99, 179, 237, 0.25);',
    '}',
    '.sugarcubes-browser__table tbody tr:hover {',
    '    background: rgba(99, 179, 237, 0.18);',
    '}',
    '.sugarcubes-browser__empty {',
    '    padding: 24px;',
    '    text-align: center;',
    '    font-size: 0.95rem;',
    '    opacity: 0.7;',
    '}',
    '.sugarcubes-browser__detail {',
    '    flex: 1 1 45%;',
    '    min-width: 0;',
    '    display: flex;',
    '    flex-direction: column;',
    '    gap: 12px;',
    '    border: 1px solid rgba(128, 128, 128, 0.18);',
    '    border-radius: 12px;',
    '    padding: 16px;',
    '    overflow: hidden;',
    '    max-height: 400px;',
    '}',
    '.sugarcubes-browser__detail-body {',
    '    display: flex;',
    '    flex-direction: column;',
    '    gap: 12px;',
    '    overflow-y: auto;',
    '    min-height: 0;',
    '    flex: 1 1 auto;',
    '    margin: -18px -16px -16px;',
    '    padding: 18px 16px 16px;',
    '}',
    '.sugarcubes-browser__detail h3 {',
    '    margin: 0;',
    '    font-size: 1.05rem;',
    '}',
    '.sugarcubes-browser__detail-header {',
    '    display: flex;',
    '    align-items: center;',
    '    justify-content: space-between;',
    '    gap: 12px;',
    '    padding: 8px 12px;',
    '    margin: -16px -16px 6px;',
    '    background: rgba(128, 128, 128, 0.08);',
    '    border-bottom: 1px solid rgba(128, 128, 128, 0.12);',
    '    border-radius: 12px 12px 0 0;',
    '}',
    '.sugarcubes-browser__detail-title {',
    '    display: inline-flex;',
    '    align-items: center;',
    '    gap: 6px;',
    '    min-width: 0;',
    '}',
    '.sugarcubes-browser__detail-icon {',
    '    width: 28px;',
    '    height: 28px;',
    '    flex-basis: 28px;',
    '}',
    '.sugarcubes-browser__detail-title h3 {',
    '    min-width: 0;',
    '    overflow: hidden;',
    '    text-overflow: ellipsis;',
    '    white-space: nowrap;',
    '}',
    '.sugarcubes-browser__detail-title h3 + .sugarcubes-browser__version-control {',
    '    margin-left: 4px;',
    '}',
    '.sugarcubes-browser__tag {',
    '    display: inline-flex;',
    '    align-items: center;',
    '    padding: 2px 8px;',
    '    margin: 2px;',
    '    background: rgba(99, 179, 237, 0.18);',
    '    border-radius: 999px;',
    '    font-size: 0.75rem;',
    '}',
    '.sugarcubes-browser__meta {',
    '    display: flex;',
    '    flex-direction: column;',
    '    gap: 6px;',
    '    font-size: 0.85rem;',
    '}',
    '.sugarcubes-browser__favorite {',
    '    border: none;',
    '    background: transparent;',
    '    color: #f6c744;',
    '    cursor: pointer;',
    '    font-size: 1.1rem;',
    '}',
    '.sugarcubes-browser__favorite.is-empty {',
    '    color: rgba(128, 128, 128, 0.6);',
    '}',
    '.sugarcubes-browser__favorite.is-locked {',
    '    color: rgba(128, 128, 128, 0.7);',
    '}',
    '.sugarcubes-browser__favorite-indicator {',
    '    color: rgba(128, 128, 128, 0.65);',
    '    font-size: 1rem;',
    '    line-height: 1;',
    '    display: inline-block;',
    '    width: 16px;',
    '    text-align: center;',
    '    pointer-events: none;',
    '}',
    '.sugarcubes-browser__dirty-dot {',
    '    display: inline-block;',
    '    width: 8px;',
    '    height: 8px;',
    '    margin-left: 6px;',
    '    border-radius: 999px;',
    '    background: #d3514a;',
    '    vertical-align: middle;',
    '}',
    '.sugarcubes-browser__table tbody tr.is-dirty td:first-child {',
    '    font-weight: 600;',
    '}',
    '.sugarcubes-browser__detail-actions {',
    '    display: inline-flex;',
    '    align-items: center;',
    '    gap: 6px;',
    '}',
    '.sugarcubes-browser__detail-actions button,',
    '.sugarcubes-browser__detail-title .sugarcubes-browser__favorite {',
    '    width: 28px;',
    '    height: 28px;',
    '    display: inline-flex;',
    '    align-items: center;',
    '    justify-content: center;',
    '    line-height: 1;',
    '    font-size: 1.05rem;',
    '}',
    '.sugarcubes-browser__detail-actions .sugarcubes-browser__place,',
    '.sugarcubes-browser__detail-actions .sugarcubes-browser__delete {',
    '    padding: 0;',
    '}',
    '.sugarcubes-browser__detail-actions i {',
    '    font-size: 1rem;',
    '    line-height: 1;',
    '}',
    '.sugarcubes-browser__version-control {',
    '    position: relative;',
    '    display: inline-flex;',
    '    align-items: center;',
    '    flex: 0 0 auto;',
    '    gap: 2px;',
    '    width: auto;',
    '    min-width: 0;',
    '}',
    '.sugarcubes-browser__version-prefix {',
    '    font-size: 0.78rem;',
    '    line-height: 1;',
    '    opacity: 0.72;',
    '    user-select: none;',
    '}',
    '.sugarcubes-browser__version-input-shell {',
    '    display: inline-flex;',
    '    align-items: center;',
    '    height: 28px;',
    '    border-radius: 6px;',
    '    border: 1px solid rgba(128, 128, 128, 0.28);',
    '    background: rgba(255, 255, 255, 0.88);',
    '    overflow: hidden;',
    '}',
    '.sugarcubes-browser__version-input {',
    '    width: 7ch;',
    '    height: 28px;',
    '    padding: 3px 4px 3px 6px;',
    '    border: none;',
    '    background: transparent;',
    '    color: inherit;',
    '    font-size: 0.78rem;',
    '    line-height: 1;',
    '    outline: none;',
    '}',
    '.sugarcubes-browser__version-toggle {',
    '    width: 18px;',
    '    height: 28px;',
    '    border: none;',
    '    border-left: 1px solid rgba(128, 128, 128, 0.18);',
    '    background: transparent;',
    '    color: inherit;',
    '    cursor: pointer;',
    '    position: relative;',
    '}',
    '.sugarcubes-browser__version-toggle::before {',
    '    content: "";',
    '    position: absolute;',
    '    left: 50%;',
    '    top: 50%;',
    '    transform: translate(-50%, -25%);',
    '    border-left: 4px solid transparent;',
    '    border-right: 4px solid transparent;',
    '    border-top: 5px solid currentColor;',
    '    opacity: 0.72;',
    '}',
    '.sugarcubes-browser__version-input:disabled,',
    '.sugarcubes-browser__version-toggle:disabled {',
    '    cursor: default;',
    '    opacity: 0.7;',
    '}',
    'body.dark-theme .sugarcubes-browser__version-input-shell {',
    '    background: rgba(18, 20, 23, 0.9);',
    '    border-color: rgba(255, 255, 255, 0.12);',
    '}',
    '.sugarcubes-browser__version-control.is-error .sugarcubes-browser__version-input-shell {',
    '    border-color: rgba(200, 90, 90, 0.65);',
    '    color: rgba(200, 90, 90, 0.95);',
    '}',
    '.sugarcubes-browser__version-listbox {',
    '    position: absolute;',
    '    top: calc(100% + 4px);',
    '    left: 12px;',
    '    right: 0;',
    '    z-index: 7;',
    '    min-width: 0;',
    '    max-height: 160px;',
    '    overflow-y: auto;',
    '    display: flex;',
    '    flex-direction: column;',
    '    gap: 2px;',
    '    margin: 0;',
    '    padding: 6px;',
    '    list-style: none;',
    '    border: 1px solid rgba(128, 128, 128, 0.2);',
    '    border-radius: 6px;',
    '    background: var(--sugarcubes-browser-bg, #ffffff);',
    '    box-shadow: 0 12px 24px rgba(0, 0, 0, 0.16);',
    '}',
    '.sugarcubes-browser__version-listbox[hidden] {',
    '    display: none;',
    '}',
    '.sugarcubes-browser__version-option {',
    '    padding: 5px 7px;',
    '    border-radius: 6px;',
    '    cursor: pointer;',
    '    font-size: 0.78rem;',
    '    line-height: 1.1;',
    '}',
    '.sugarcubes-browser__version-option.is-highlighted,',
    '.sugarcubes-browser__version-option:hover {',
    '    background: rgba(99, 179, 237, 0.18);',
    '}',
    '.sugarcubes-browser__version-option[aria-selected="true"] {',
    '    font-weight: 600;',
    '}',
    'body.dark-theme .sugarcubes-browser__version-listbox {',
    '    background: #121417;',
    '    border-color: rgba(255, 255, 255, 0.08);',
    '}',
    '.sugarcubes-browser__edit-field {',
    '    display: grid;',
    '    grid-template-columns: 120px 1fr;',
    '    gap: 8px;',
    '    align-items: start;',
    '    font-size: 0.85rem;',
    '}',
    '.sugarcubes-browser__edit-field label {',
    '    font-weight: 600;',
    '}',
    '.sugarcubes-browser__edit-field input,',
    '.sugarcubes-browser__edit-field textarea {',
    '    width: 100%;',
    '    font-size: 0.85rem;',
    '    padding: 6px 8px;',
    '    border-radius: 6px;',
    '    border: 1px solid rgba(128, 128, 128, 0.3);',
    '    background: rgba(255, 255, 255, 0.9);',
    '    color: inherit;',
    '}',
    '.sugarcubes-browser__edit-field input[readonly] {',
    '    opacity: 0.7;',
    '}',
    '.sugarcubes-browser__title-input {',
    '    width: 100%;',
    '    font-size: 1.02rem;',
    '    font-weight: 600;',
    '    padding: 4px 6px;',
    '    border-radius: 6px;',
    '    border: 1px solid rgba(128, 128, 128, 0.3);',
    '    background: rgba(255, 255, 255, 0.9);',
    '    color: inherit;',
    '}',
    'body.dark-theme .sugarcubes-browser__title-input {',
    '    background: rgba(18, 20, 23, 0.9);',
    '    border-color: rgba(255, 255, 255, 0.12);',
    '}',
    '.sugarcubes-browser__model-autocomplete {',
    '    position: relative;',
    '    display: flex;',
    '    flex-direction: column;',
    '    gap: 6px;',
    '}',
    '.sugarcubes-browser__model-text-input {',
    '    width: 100%;',
    '    padding: 6px 8px;',
    '    border-radius: 6px;',
    '    border: 1px solid rgba(128, 128, 128, 0.3);',
    '    background: rgba(255, 255, 255, 0.9);',
    '    color: inherit;',
    '    font-size: 0.85rem;',
    '}',
    'body.dark-theme .sugarcubes-browser__model-text-input {',
    '    background: rgba(18, 20, 23, 0.9);',
    '    border-color: rgba(255, 255, 255, 0.12);',
    '}',
    '.sugarcubes-browser__model-suggestions {',
    '    position: absolute;',
    '    top: calc(100% + 4px);',
    '    left: 0;',
    '    right: 0;',
    '    z-index: 6;',
    '    display: flex;',
    '    flex-direction: column;',
    '    gap: 2px;',
    '    max-height: 180px;',
    '    overflow-y: auto;',
    '    padding: 6px;',
    '    border: 1px solid rgba(128, 128, 128, 0.2);',
    '    border-radius: 8px;',
    '    background: var(--sugarcubes-browser-bg, #ffffff);',
    '    box-shadow: 0 12px 24px rgba(0, 0, 0, 0.16);',
    '}',
    '.sugarcubes-browser__model-suggestions[hidden] {',
    '    display: none;',
    '}',
    '.sugarcubes-browser__model-suggestion {',
    '    border: none;',
    '    background: transparent;',
    '    color: inherit;',
    '    text-align: left;',
    '    padding: 6px 8px;',
    '    border-radius: 6px;',
    '    cursor: pointer;',
    '    font-size: 0.82rem;',
    '}',
    '.sugarcubes-browser__model-suggestion:hover,',
    '.sugarcubes-browser__model-suggestion.is-highlighted {',
    '    background: rgba(99, 179, 237, 0.18);',
    '}',
    'body.dark-theme .sugarcubes-browser__model-suggestions {',
    '    background: #121417;',
    '    border-color: rgba(255, 255, 255, 0.08);',
    '}',
    '.sugarcubes-browser__edit-textarea {',
    '    width: 100%;',
    '    font-size: 0.85rem;',
    '    padding: 6px 8px;',
    '    border-radius: 6px;',
    '    border: 1px solid rgba(128, 128, 128, 0.3);',
    '    background: rgba(255, 255, 255, 0.9);',
    '    color: inherit;',
    '}',
    '.sugarcubes-browser__lineage-clear {',
    '    margin-top: 10px;',
    '    border: 1px solid rgba(128, 128, 128, 0.4);',
    '    background: transparent;',
    '    color: inherit;',
    '    border-radius: 6px;',
    '    padding: 6px 10px;',
    '    font-size: 0.8rem;',
    '    cursor: pointer;',
    '}',
    '.sugarcubes-browser__lineage-clear:hover {',
    '    border-color: rgba(128, 128, 128, 0.7);',
    '}',
    'body.dark-theme .sugarcubes-browser__edit-field input,',
    'body.dark-theme .sugarcubes-browser__edit-field textarea {',
    '    background: rgba(18, 20, 23, 0.9);',
    '    border-color: rgba(255, 255, 255, 0.12);',
    '}',
    'body.dark-theme .sugarcubes-browser__edit-textarea {',
    '    background: rgba(18, 20, 23, 0.9);',
    '    border-color: rgba(255, 255, 255, 0.12);',
    '}',
    '.sugarcubes-browser__place {',
    '    border: none;',
    '    background: transparent;',
    '    color: rgba(90, 200, 120, 0.9);',
    '    cursor: pointer;',
    '    display: inline-flex;',
    '    align-items: center;',
    '    justify-content: center;',
    '    padding: 2px;',
    '    font-size: 1.05rem;',
    '}',
    '.sugarcubes-browser__place:disabled {',
    '    opacity: 0.4;',
    '    cursor: not-allowed;',
    '}',
    '.sugarcubes-browser__place .mdi-arrow-right-bold {',
    '    display: none;',
    '}',
    '.sugarcubes-browser__place:hover .mdi-arrow-right-bold {',
    '    display: inline-block;',
    '}',
    '.sugarcubes-browser__place:hover .mdi-arrow-right-bold-outline {',
    '    display: none;',
    '}',
    '.sugarcubes-browser__edit {',
    '    border: none;',
    '    background: transparent;',
    '    color: rgba(90, 140, 240, 0.9);',
    '    cursor: pointer;',
    '    display: inline-flex;',
    '    align-items: center;',
    '    justify-content: center;',
    '    padding: 2px;',
    '    font-size: 1rem;',
    '}',
    '.sugarcubes-browser__edit:disabled {',
    '    opacity: 0.4;',
    '    cursor: not-allowed;',
    '}',
    '.sugarcubes-browser__edit .mdi-pencil {',
    '    display: none;',
    '}',
    '.sugarcubes-browser__edit:hover .mdi-pencil {',
    '    display: inline-block;',
    '}',
    '.sugarcubes-browser__edit:hover .mdi-pencil-outline {',
    '    display: none;',
    '}',
    '.sugarcubes-browser__edit-save {',
    '    border: none;',
    '    background: transparent;',
    '    color: rgba(90, 140, 240, 0.9);',
    '    cursor: pointer;',
    '    display: inline-flex;',
    '    align-items: center;',
    '    justify-content: center;',
    '    padding: 2px;',
    '    font-size: 1rem;',
    '}',
    '.sugarcubes-browser__edit-save:disabled {',
    '    opacity: 0.4;',
    '    cursor: not-allowed;',
    '}',
    '.sugarcubes-browser__edit-save .mdi-content-save {',
    '    display: none;',
    '}',
    '.sugarcubes-browser__edit-save:hover .mdi-content-save {',
    '    display: inline-block;',
    '}',
    '.sugarcubes-browser__edit-save:hover .mdi-content-save-outline {',
    '    display: none;',
    '}',
    '.sugarcubes-browser__edit-cancel {',
    '    border: none;',
    '    background: transparent;',
    '    color: rgba(190, 70, 70, 0.9);',
    '    cursor: pointer;',
    '    display: inline-flex;',
    '    align-items: center;',
    '    justify-content: center;',
    '    padding: 2px;',
    '    font-size: 1rem;',
    '}',
    '.sugarcubes-browser__edit-cancel:disabled {',
    '    opacity: 0.4;',
    '    cursor: not-allowed;',
    '}',
    '.sugarcubes-browser__edit-cancel .mdi-close-circle {',
    '    display: none;',
    '}',
    '.sugarcubes-browser__edit-cancel:hover .mdi-close-circle {',
    '    display: inline-block;',
    '}',
    '.sugarcubes-browser__edit-cancel:hover .mdi-close-circle-outline {',
    '    display: none;',
    '}',
    '.sugarcubes-browser__detail-actions .sugarcubes-browser__action-hidden {',
    '    display: none;',
    '}',
    '.sugarcubes-browser__action-placeholder {',
    '    visibility: hidden;',
    '}',
    '.sugarcubes-browser__delete {',
    '    border: none;',
    '    background: transparent;',
    '    color: rgba(200, 90, 90, 0.9);',
    '    cursor: pointer;',
    '    display: inline-flex;',
    '    align-items: center;',
    '    justify-content: center;',
    '    padding: 2px;',
    '    font-size: 1rem;',
    '}',
    '.sugarcubes-browser__delete:disabled {',
    '    opacity: 0.4;',
    '    cursor: not-allowed;',
    '}',
    '.sugarcubes-browser__delete .mdi-trash-can {',
    '    display: none;',
    '}',
    '.sugarcubes-browser__delete:hover .mdi-trash-can {',
    '    display: inline-block;',
    '}',
    '.sugarcubes-browser__delete:hover .mdi-trash-can-outline {',
    '    display: none;',
    '}',
    '.sugarcubes-browser__detail pre {',
    '    white-space: pre-wrap;',
    '    font-family: inherit;',
    '    font-size: 0.9rem;',
    '}',
    '.sugarcubes-browser__preview {',
    '    border: 1px solid rgba(128, 128, 128, 0.18);',
    '    border-radius: 12px;',
    '    padding: 12px;',
    '    display: flex;',
    '    align-items: center;',
    '    justify-content: center;',
    '    min-height: 120px;',
    '    position: relative;',
    '}',
    '.sugarcubes-browser__preview-canvas {',
    '    width: 100%;',
    '    display: none;',
    '    cursor: grab;',
    '}',
    '.sugarcubes-browser__preview-canvas.is-dragging {',
    '    cursor: grabbing;',
    '}',
    '.sugarcubes-browser__preview-status {',
    '    font-size: 0.85rem;',
    '    opacity: 0.7;',
    '    text-align: center;',
    '}',
];
/**
 * Inject browser styles.
 */
export function injectBrowserStyles(documentRef) {
    if (!documentRef || documentRef.getElementById(STYLE_ID)) {
        return;
    }
    const style = documentRef.createElement('style');
    style.id = STYLE_ID;
    style.textContent = browserStyles.join('\n');
    documentRef.head?.appendChild(style);
}
